sync:
  - from: xiaomihome
    username: 'pzabalain@yahoo.es'
    password: '1001Motor$xia'
    region: de
    model: yunmai.scales.ms104
  - to: garmin
    username: 'pzabalain@yahoo.es'
    password: '1001Motor$gar'
